
import type { Product, Order } from './types';

export const mockProducts: Product[] = [
  {
    id: 'prod_001',
    name: 'Pro 6 Bluetooth Headset',
    price: 777,
    currency: 'PKR',
    quantity: 100,
    imageUrl: 'https://picsum.photos/300/300?random=1',
    data_ai_hint: 'bluetooth headset',
    category: 'Electronics',
    description: 'High-quality Pro 6 Bluetooth Headset with immersive sound and long battery life. Perfect for music, calls, and gaming.',
    shortDescription: 'High-quality Pro 6 Bluetooth Headset...',
    features: ['Noise Cancellation', 'Long Battery Life', 'Comfortable Fit', 'Quick Pairing'],
    rating: 4.8,
    reviewsCount: 256,
    onSale: false,
    bestSeller: true,
  },
  {
    id: 'prod_002',
    name: 'Beaded Bracelet',
    price: 306,
    currency: 'PKR',
    quantity: 200,
    imageUrl: 'https://picsum.photos/300/300?random=2',
    data_ai_hint: 'beaded bracelet',
    category: 'Jewelry',
    description: 'A beautifully handcrafted beaded bracelet. A stylish accessory for any occasion, made with high-quality materials.',
    shortDescription: 'A beautifully handcrafted beaded bracelet...',
    features: ['Handcrafted Design', 'High-quality beads', 'Adjustable size', 'Elegant look'],
    rating: 4.9,
    reviewsCount: 512,
    onSale: true,
    originalPrice: 450,
    bestSeller: true,
  },
  {
    id: 'prod_003',
    name: 'Wireless Earbuds',
    price: 767,
    currency: 'PKR',
    quantity: 150,
    imageUrl: 'https://picsum.photos/300/300?random=3',
    data_ai_hint: 'wireless earbuds',
    category: 'Electronics',
    description: 'Compact and powerful wireless earbuds with crystal clear audio. Comes with a portable charging case for on-the-go power.',
    shortDescription: 'Compact and powerful wireless earbuds...',
    features: ['Crystal Clear Audio', 'Portable Charging Case', 'Secure Fit', 'Touch Controls'],
    rating: 4.7,
    reviewsCount: 189,
    onSale: false,
    bestSeller: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord_001',
    customerName: 'Alice Johnson',
    email: 'alice@example.com',
    phone: '+1234567890',
    address: '123 Dream Lane',
    city: 'Wonderland',
    province: 'Fantasyland',
    country: 'Imagi Nation',
    zip: '12345',
    items: [
      { ...mockProducts[0], cartQuantity: 1 },
      { ...mockProducts[2], cartQuantity: 1 },
    ],
    subtotal: 1544,
    deliveryTotal: 250,
    total: 1794,
    currency: 'PKR',
    status: 'Shipped',
    createdAt: new Date('2023-10-26T10:00:00Z'),
    paymentMethod: 'Credit Card',
  },
];
